### ISSUE TITLE
Move to DB-approach

### ISSUE THREAD

**Issue by anaclumos** [anaclumos/heimdall#13]
- Front-end: CF Pages
- Back-end: Supabase/PlanetScale, haven't decided yet

**Comment by dreammis** [comment]
I stumbled across this repository by accident, and I really appreciate your vision for starting this😊. There must be many people who will benefit from this.
The cdn of cf is great, and the access speed has been significantly improved

**Comment by anaclumos** [comment]
@dreammis Thanks! I am currently using Vercel but facing troubles. [Vercel Incident Report (April 2023) @ Sunghyun Cho](https://cho.sh/r/B1F73D)

I plan on continuously improving this project; please share it with your friends!
