### ISSUE TITLE
Problem accessing websites behind Cloudflare?

### ISSUE THREAD

**Issue by PeterDaveHello** [anaclumos/heimdall#44]
- https://hn.cho.sh/2023/08/07/#i-went-to-50-different-dentists-almost-all-gave-a-different-diagnosis-2022

> - The website rd.com is employing Cloudflare as a security service to safeguard against online attacks.
> - The user has been restricted from accessing the website and is advised to enable cookies and reach out to the site owner for a resolution.
> - No additional context or information is provided.

- https://hn.cho.sh/2023/08/06/#new-acoustic-attack-steals-data-from-keystrokes-with-95-accuracy

> - The website www.bleepingcomputer.com is using Cloudflare to enhance performance and security.
> - Before allowing users to proceed, the website checks the security of their connection.
> - This measure aims to ensure a safe browsing experience for its visitors.

**Comment by anaclumos** [comment]
Resolved for now. There's no real fix to this.

**Comment by anaclumos** [comment]
[Blocked by Cloudflare](https://jrhawley.ca/2023/08/07/blocked-by-cloudflare)
