### ISSUE TITLE
Contents of the Reactions section is similar to the summary

### ISSUE THREAD

**Issue by rishubil** [anaclumos/heimdall#54]
It's not literally the same string, but the summary and HN Reaction appear to be the same thing.
I think it's been like this for a few days now.

**Comment by anaclumos** [comment]
Will look into it. Can you remind me of your locale?

**Comment by anaclumos** [comment]
Turns out, I was using the same context. How'd you find it 😭? I'm impressed. Thank you so much for being such an enthusiastic reader!
